/**
 * Frameworks overview motion contract.
 *
 * Shared overview timings are sourced from the Atlas overview interaction
 * vocabulary. Frameworks keeps geometry transitions and breath staggering
 * local because those are part of its spatial expression.
 */

import {
  ATLAS_OVERVIEW_CHROME_REVEAL_DELAY,
  ATLAS_OVERVIEW_DRAWER_CLOSE_DURATION,
  ATLAS_OVERVIEW_DRAWER_OPEN_DURATION,
  ATLAS_OVERVIEW_LABEL_REVEAL_DELAY,
  ATLAS_OVERVIEW_READING_HANDOFF_DURATION,
  ATLAS_OVERVIEW_REDUCED_DRAWER_DURATION,
  ATLAS_OVERVIEW_REDUCED_HANDOFF_DURATION,
  ATLAS_OVERVIEW_REDUCED_RETURN_DURATION,
  ATLAS_OVERVIEW_RETURN_DURATION,
  ATLAS_OVERVIEW_SELECTION_PULSE_DURATION,
} from "../overview/atlasOverviewMotion";

export const FRAMEWORK_POSITION_TRANSITION =
  "transform 0.52s cubic-bezier(0.16,1,0.3,1)";

export const FRAMEWORK_FADE_TRANSITION = "opacity 0.32s ease";

export const FRAMEWORK_SELECTION_PULSE_DURATION =
  ATLAS_OVERVIEW_SELECTION_PULSE_DURATION;
export const FRAMEWORK_DRAWER_CLOSE_DURATION =
  ATLAS_OVERVIEW_DRAWER_CLOSE_DURATION;
export const FRAMEWORK_DRAWER_OPEN_DURATION =
  ATLAS_OVERVIEW_DRAWER_OPEN_DURATION;
export const FRAMEWORK_LABEL_REVEAL_DELAY =
  ATLAS_OVERVIEW_LABEL_REVEAL_DELAY;
export const FRAMEWORK_CHROME_REVEAL_DELAY =
  ATLAS_OVERVIEW_CHROME_REVEAL_DELAY;
export const FRAMEWORK_REDUCED_MOTION_DRAWER_DURATION =
  ATLAS_OVERVIEW_REDUCED_DRAWER_DURATION;

export const FRAMEWORK_BREATH_DELAYS = [0, 0.8, 1.5, 2.2, 2.9] as const;

export const FRAMEWORK_READING_HANDOFF_DURATION =
  ATLAS_OVERVIEW_READING_HANDOFF_DURATION;
export const FRAMEWORK_READING_REDUCED_HANDOFF_DURATION =
  ATLAS_OVERVIEW_REDUCED_HANDOFF_DURATION;
export const FRAMEWORK_RETURN_DURATION =
  ATLAS_OVERVIEW_RETURN_DURATION;
export const FRAMEWORK_RETURN_REDUCED_DURATION =
  ATLAS_OVERVIEW_REDUCED_RETURN_DURATION;
